#! /bin/sh

if [ "$SPKG_LOCAL" = "" ]; then
   echo "SPKG_LOCAL undefined ... exiting";
   echo "Maybe run 'qsnake --shell'?"
   exit 1
fi


set -e

cd src
make profile-build ARCH=x86-64
cp stockfish "$SPKG_LOCAL"/bin
